### ISSUE TITLE
Package Naming

### ISSUE THREAD

**Issue by trinker** [quanteda/nsyllable#1]
@kbenoit Once upon a time I had a [package on CRAN called syllable](https://cran.r-project.org/web/packages/syllable/index.html).  I archived it.  If you prefer the name syllable and was avoiding it because the name is CRAN taken I'm very open to figuring out if/how you can use the name.  Feel free to close this without discussion if this is not something you're interested in but figured I'd throw it out there before you devlop this too much further.

**Comment by kbenoit** [comment]
Hi Tyler! Wow, how did I not know about that? I just checked your repos and found it. Looks like it could replace this package.

`nsyllable()` is current a function in **quanteda** used only by the readability function. It also works only in English. Like in your package, it looks up words - but does so by storing the syllables as a named integer vector where the names are used for the indexing. I found that this was the fastest method in R, but maybe your approach is even faster.

Why'd you archive **syllable**? That could serve as the replacement we need. Basically we're trying to offload functions from **quanteda** that are easily separated and (maybe more importantly) can be used independently of **quanteda** for other purposes. The **stopwords** package is a good example. (It even has a `use_stopwords()` function as in the `usethis::use_etc()` functions to add it as a reexport for package developers.)

Would be happy to discuss ways to collaborate here.

**Comment by trinker** [comment]
I archived it because I built it for a [readability package](https://cran.r-project.org/web/packages/readability/index.html) (also archived from CRAN).  Like you, I pulled the useful syllable guts out as it's own package.  I had retired readability for this reason: https://github.com/trinker/readability/issues/6#issuecomment-393727892.  Overall, the reason for retiring these things was that the last text workshop I attended I felt it was imperative to unify more of the R text analysis framework, to remove the growing number of choices.

The named vectors approach for simple lookups is quite performant (better than list lookups or environment) in my measurments as well.  At the time I may have done some trialing at larger n and foound data.table better but can not recall.  Part of the time in the lookup for data.table is creating the keys but if the dictionary is stored with keys already set it reduces this overhead.  All this to say that I don't recall if using data.table over named  vectors was an intentional design or a design of omission.

But feel free to take anything that's of use including 'syllable' and 'readability' as package names (just have to figure out how to do this with CRAN if that is your desire).

**Comment by kbenoit** [comment]
Getting back to this, thanks for the offer @trinker, I did look closely at your source code for the syllable repository. 

In the end I went for an extremely simple package that simply encapsulates the syllable counting function, with just one function `nsyllable()`, which returns the number of syllables in a character vector.

In fact it's my first and only package with zero dependencies!
